[package]
name = "guest01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = { version="0.5.1", default-features=false }
log = { version="0.4.11", default-features=false }