on:
  push:
    branches: [ master ]
  pull_request:
  merge_group:

name: Code formatting check

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Run Rustfmt
        run: cargo fmt --all -- --check --verbose
